In [2]:
import geopandas as gpd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd
from data_gen import NFLDataGenerator
from distances import calc_dist

In [3]:
SNAP_EVENTS = ['ball_snap', 'autoevent_ballsnap']
NONSNAP_EVENTS = ['ball_snap', 'autoevent_ballsnap','None']
PASS_ONLY_PASSRESULTS = ['C','I','IN']
POCKET_AREA_BUCKETS = [0, 5, 10, 15, np.Inf]

In [24]:
all_play_cts = []
for i in range(1,9):
    week_data_gen = NFLDataGenerator(week_ids=[i])
    snap_df = (week_data_gen.week_df
               .query('event.isin(@SNAP_EVENTS)')
               .groupby(['gameId','playId'])
               ['time'].min()
               .reset_index()
               .rename({'time':'snap_time'}, axis=1))

    nonsnap_df = (week_data_gen.week_df
               .merge(snap_df, how='left', on=['gameId','playId'])
               .query('time > snap_time')
               .query('~event.isin(@NONSNAP_EVENTS)')
               .groupby(['gameId','playId'])
               [['time','frameId']].min()
               .reset_index()
               .rename({'time':'nonsnap_time'},axis=1))

    pass_play_only_df = (
        week_data_gen.plays_df
        .query('pff_playAction == 0')
        .query('passResult.isin(@PASS_ONLY_PASSRESULTS)')
    )

    polygon_area_df = nonsnap_df.merge(week_data_gen.pocket_poly_df, how='left',on=['gameId', 'frameId', 'playId']).drop('pocket_polygon', axis=1)
    polygon_area_df = polygon_area_df.merge(pass_play_only_df, how='inner', on=['gameId', 'playId'])
    polygon_area_df['pocket_area_buckets'] = pd.cut(polygon_area_df['pocket_area'], POCKET_AREA_BUCKETS)

    play_cts = polygon_area_df.groupby(['pocket_area_buckets','passResult'])['playId'].count().reset_index().rename({'playId':'play_cts'},axis=1)
    play_cts = (play_cts
                .merge(play_cts
                       .groupby('pocket_area_buckets')
                       ['play_cts'].sum()
                       .reset_index()
                       .rename({'play_cts':'tot_play_cts'}, axis=1), how='left', on='pocket_area_buckets')
                .assign(
                    play_pct = lambda x: x['play_cts']/x['tot_play_cts']))
    all_play_cts.append(play_cts)

In [25]:
for df in all_play_cts:
    display(df.pivot(index='pocket_area_buckets', columns='passResult', values=['play_cts','tot_play_cts', 'play_pct']))

                    play_cts             tot_play_cts                play_pct  \
passResult                 C      I   IN            C      I     IN         C
pocket_area_buckets
(0.0, 5.0]              68.0   51.0  2.0        121.0  121.0  121.0  0.561983
(5.0, 10.0]            132.0   91.0  8.0        231.0  231.0  231.0  0.571429
(10.0, 15.0]           184.0  102.0  2.0        288.0  288.0  288.0  0.638889
(15.0, inf]            125.0   68.0  5.0        198.0  198.0  198.0  0.631313


passResult                  I        IN
pocket_area_buckets
(0.0, 5.0]           0.421488  0.016529
(5.0, 10.0]          0.393939  0.034632
(10.0, 15.0]         0.354167  0.006944
(15.0, inf]          0.343434  0.025253

                    play_cts            tot_play_cts                play_pct  \
passResult                 C     I   IN            C      I     IN         C
pocket_area_buckets
(0.0, 5.0]              45.0  20.0  5.0         70.0   70.0   70.0  0.642857
(5.0, 10.0]            115.0  70.0  7.0        192.0  192.0  192.0  0.598958
(10.0, 15.0]           158.0  74.0  9.0        241.0  241.0  241.0  0.655602
(15.0, inf]            127.0  64.0  3.0        194.0  194.0  194.0  0.654639


passResult                  I        IN
pocket_area_buckets
(0.0, 5.0]           0.285714  0.071429
(5.0, 10.0]          0.364583  0.036458
(10.0, 15.0]         0.307054  0.037344
(15.0, inf]          0.329897  0.015464

                    play_cts            tot_play_cts                play_pct  \
passResult                 C     I   IN            C      I     IN         C
pocket_area_buckets
(0.0, 5.0]              55.0  53.0  8.0        116.0  116.0  116.0  0.474138
(5.0, 10.0]            130.0  65.0  1.0        196.0  196.0  196.0  0.663265
(10.0, 15.0]           200.0  94.0  4.0        298.0  298.0  298.0  0.671141
(15.0, inf]            100.0  71.0  7.0        178.0  178.0  178.0  0.561798


passResult                  I        IN
pocket_area_buckets
(0.0, 5.0]           0.456897  0.068966
(5.0, 10.0]          0.331633  0.005102
(10.0, 15.0]         0.315436  0.013423
(15.0, inf]          0.398876  0.039326

                    play_cts            tot_play_cts                play_pct  \
passResult                 C     I   IN            C      I     IN         C
pocket_area_buckets
(0.0, 5.0]              40.0  43.0  3.0         86.0   86.0   86.0  0.465116
(5.0, 10.0]            119.0  94.0  1.0        214.0  214.0  214.0  0.556075
(10.0, 15.0]           162.0  82.0  4.0        248.0  248.0  248.0  0.653226
(15.0, inf]            100.0  80.0  3.0        183.0  183.0  183.0  0.546448


passResult                  I        IN
pocket_area_buckets
(0.0, 5.0]           0.500000  0.034884
(5.0, 10.0]          0.439252  0.004673
(10.0, 15.0]         0.330645  0.016129
(15.0, inf]          0.437158  0.016393

                    play_cts             tot_play_cts                play_pct  \
passResult                 C      I   IN            C      I     IN         C
pocket_area_buckets
(0.0, 5.0]              41.0   34.0  5.0         80.0   80.0   80.0  0.512500
(5.0, 10.0]            117.0   80.0  6.0        203.0  203.0  203.0  0.576355
(10.0, 15.0]           165.0  110.0  3.0        278.0  278.0  278.0  0.593525
(15.0, inf]            124.0   55.0  5.0        184.0  184.0  184.0  0.673913


passResult                  I        IN
pocket_area_buckets
(0.0, 5.0]           0.425000  0.062500
(5.0, 10.0]          0.394089  0.029557
(10.0, 15.0]         0.395683  0.010791
(15.0, inf]          0.298913  0.027174

                    play_cts             tot_play_cts                play_pct  \
passResult                 C     I    IN            C      I     IN         C
pocket_area_buckets
(0.0, 5.0]              50.0  31.0   4.0         85.0   85.0   85.0  0.588235
(5.0, 10.0]             97.0  66.0   5.0        168.0  168.0  168.0  0.577381
(10.0, 15.0]           151.0  76.0  10.0        237.0  237.0  237.0  0.637131
(15.0, inf]            117.0  60.0   1.0        178.0  178.0  178.0  0.657303


passResult                  I        IN
pocket_area_buckets
(0.0, 5.0]           0.364706  0.047059
(5.0, 10.0]          0.392857  0.029762
(10.0, 15.0]         0.320675  0.042194
(15.0, inf]          0.337079  0.005618

                    play_cts            tot_play_cts                play_pct  \
passResult                 C     I   IN            C      I     IN         C
pocket_area_buckets
(0.0, 5.0]              36.0  30.0  2.0         68.0   68.0   68.0  0.529412
(5.0, 10.0]             94.0  66.0  6.0        166.0  166.0  166.0  0.566265
(10.0, 15.0]           123.0  68.0  7.0        198.0  198.0  198.0  0.621212
(15.0, inf]             91.0  67.0  3.0        161.0  161.0  161.0  0.565217


passResult                  I        IN
pocket_area_buckets
(0.0, 5.0]           0.441176  0.029412
(5.0, 10.0]          0.397590  0.036145
(10.0, 15.0]         0.343434  0.035354
(15.0, inf]          0.416149  0.018634

                    play_cts             tot_play_cts                play_pct  \
passResult                 C     I    IN            C      I     IN         C
pocket_area_buckets
(0.0, 5.0]              53.0  33.0   4.0         90.0   90.0   90.0  0.588889
(5.0, 10.0]            118.0  73.0  10.0        201.0  201.0  201.0  0.587065
(10.0, 15.0]           145.0  82.0   1.0        228.0  228.0  228.0  0.635965
(15.0, inf]            108.0  77.0   4.0        189.0  189.0  189.0  0.571429


passResult                  I        IN
pocket_area_buckets
(0.0, 5.0]           0.366667  0.044444
(5.0, 10.0]          0.363184  0.049751
(10.0, 15.0]         0.359649  0.004386
(15.0, inf]          0.407407  0.021164

In [33]:
all_play_cts_df = pd.concat(all_play_cts).groupby(['pocket_area_buckets','passResult']).apply(lambda x: x['play_cts'].sum())
all_play_cts_df
# play_cts = (play_cts
#             .merge(play_cts
#                    .groupby('pocket_area_buckets')
#                    ['play_cts'].sum()
#                    .reset_index()
#                    .rename({'play_cts':'tot_play_cts'}, axis=1), how='left', on='pocket_area_buckets')
#             .assign(
#                 play_pct = lambda x: x['play_cts']/x['tot_play_cts']))

TypeError: first argument must be an iterable of pandas objects, you passed an object of type "DataFrame"

## What causes pocket areas to shrink?
* identify where the slope of the pocket areas decreases rapidly
* extract timestamps
*